### ISSUE TITLE
Crash Android with `IllegalArgumentException`

### ISSUE THREAD

**Issue by tiendn** [henninghall/react-native-date-picker#185]
**Describe the bug**
My some Android devices crash when render DatePicker
```
java.lang.IllegalArgumentException: Unterminated quote
    at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:884)
    at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:684)
    at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:623)
    at com.henninghall.date_picker.wheels.Wheel.<init>(Wheel.java:35)
    at com.henninghall.date_picker.wheels.YearWheel.<init>(YearWheel.java:21)
    at com.henninghall.date_picker.ui.Wheels.<init>(Wheels.java:50)
    at com.henninghall.date_picker.ui.UIManager.<init>(UIManager.java:27)
    at com.henninghall.date_picker.PickerView.<init>(PickerView.java:27)
    at com.henninghall.date_picker.DatePickerManager.createViewInstance(DatePickerManager.java:40)
    at com.henninghall.date_picker.DatePickerManager.createViewInstance(DatePickerManager.java:25)
    at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:180)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:987)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:958)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1039)
    at android.view.Choreographer.doCallbacks(Choreographer.java:847)
    at android.view.Choreographer.doFrame(Choreographer.java:771)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1027)
    at android.os.Handler.handleCallback(Handler.java:809)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7555)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

**Expected behavior**
Render DatePicker ok

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { tempDate: new Date() }

  render = () =>
    <DatePicker
       mode={mode}
       date={tempDate}
       collapsable
       minuteInterval={1}
       minimumDate={minimumDate}
       maximumDate={maximumDate}
       locale="vi"
       style={{ alignSelf: 'center' }}
       onDateChange={this.onDateChange}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [Android or iOS] **Android (only)**
 - React Native version [e.g. 0.59.4]: **0.62.2**
 - react-native-date-picker version [e.g. 2.5.1]: **2.7.9**

**Comment by tiendn** [comment]
It seems like http://terrapinssky.blogspot.com/2015/08/androidresolved-javalangillegalargument.html

**Comment by henninghall** [comment]
Hi, could you please include all variables in your example? mode, tempDate etc

**Comment by tiendn** [comment]
yess, this's an snapshot from my simulator.
<img width="343" alt="Screen Shot 2020-04-29 at 1 38 00 PM" src="https://user-images.githubusercontent.com/15717476/80567136-ba736c80-8a1e-11ea-8591-73ebe4dbbccc.png">

**Comment by tiendn** [comment]
yess, this's an snapshot from my simulator.
<img width="632" alt="Screen Shot 2020-04-29 at 1 40 32 PM" src="https://user-images.githubusercontent.com/15717476/80567288-02928f00-8a1f-11ea-9710-6f9b29f2252b.png">

**Comment by tiendn** [comment]
Unfortunately, I don't have the crash device

**Comment by tiendn** [comment]
Let's me explain, 
`date` && `minumumDate` I get from current time.
and `maximumDate` depend on some logic, and bigger than currentDate some days.

All value pass in with `new Date(...)`
ex: 
```
const endDay = new Date();
const maximumDate = new Date(endDay() + 2592e5)
```

**Comment by tiendn** [comment]
I tried with no locale, but it didn't work.

**Comment by henninghall** [comment]
I have tried but I don't manage to reproduce it so I would need some more help from you. 

Could you check what values are sent into SimpleDateFormat constructor at `Wheel.java` at line 35 where the crash occurs?

**Comment by tiendn** [comment]
Hmm, I have tried but failed.
Thank you for responding.

**Comment by truongduyng** [comment]
I have also met this issue. It only happens on HUAWEI and OPPO android device. I guess they did something with date format

**Comment by truongduyng** [comment]
@henninghall can we simply try/catch at that line to fallback to default format?

**Comment by HoanHearti** [comment]
any update for this issue??

**Comment by HoanHearti** [comment]
![photo_2020-06-09 13 18 02](https://user-images.githubusercontent.com/61687867/84112872-bf7eff00-aa53-11ea-88d6-41fc22c66321.jpeg)
i have issue with Huawei device

**Comment by truongduyng** [comment]
> ![photo_2020-06-09 13 18 02](https://user-images.githubusercontent.com/61687867/84112872-bf7eff00-aa53-11ea-88d6-41fc22c66321.jpeg)
> i have issue with Huawei device

hey bro, could you check what values are sent into SimpleDateFormat constructor at Wheel.java at line 35 where the crash occurs?

**Comment by truongduyng** [comment]
@henninghall finally I manage to reproduce the case. The function `getFormatPattern` return `y'` for some device types. Please help to check! I am using locale 'vi'

**Comment by truongduyng** [comment]
`EEE  ngà y  dd  MMM  nă m  y` get this also

**Comment by truongduyng** [comment]
for those who need a quick and temporary fix https://github.com/sportavn/react-native-date-picker

**Comment by tiendn** [comment]
@truongduyng  plz reduce your image size before uploaded.

It's too hard to scroll and see the content

**Comment by truongduyng** [comment]
I quoted his comment only. LOL

**Comment by henninghall** [comment]
Released a potential fix for this in version `2.7.11` @truongduyng could you check if it solves this problem?

**Comment by truongduyng** [comment]
I checked. `2.7.11` solves this problem. Thank you, guys @draperunner @henninghall

**Comment by tiendn** [comment]
Tks @truongduyng
