### ISSUE TITLE
ANR in com.henninghall.date_picker.pickers.AndroidNative.changeValueByOne in Android 11 only

### ISSUE THREAD

**Issue by guptayush** [henninghall/react-native-date-picker#502]
**Stacktrace**
main (runnable): tid=1 systid=22198 
       at com.android.internal.util.GrowingArrayUtils.insert(GrowingArrayUtils.java:151)
       at android.util.SparseArray.put(SparseArray.java:269)
       at android.widget.NumberPicker.ensureCachedScrollSelectorValue(NumberPicker.java:2016)
       at android.widget.NumberPicker.initializeSelectorWheelIndices(NumberPicker.java:1823)
       at android.widget.NumberPicker.setValueInternal(NumberPicker.java:1853)
       at android.widget.NumberPicker.scrollBy(NumberPicker.java:1182)
       at android.widget.NumberPicker.moveToFinalScrollerPosition(NumberPicker.java:887)
       at android.widget.NumberPicker.changeValueByOne(NumberPicker.java:1868)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.henninghall.date_picker.pickers.AndroidNative.changeValueByOne(AndroidNative.java:137)
       at com.henninghall.date_picker.pickers.AndroidNative.access$100(AndroidNative.java:23)
       at com.henninghall.date_picker.pickers.AndroidNative$2.run(AndroidNative.java:160)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**To Reproduce**
Not reproducible

**Smartphone:**
 - OS: [Android 11 only]
 - React Native version [0.66.4]
 - react-native-date-picker version [4.2.0]
 - 
<img width="443" alt="Screenshot 2022-04-19 at 4 24 09 PM" src="https://user-images.githubusercontent.com/34368613/163988734-5f806ee2-448e-44d7-9636-7ae633e7daec.png">

**Comment by thangpq-ahiho** [comment]
@guptayush hi, have you solved that anr?

**Comment by tarouboy** [comment]
Not just Android 11. I have got ANR reports from Android 13 as well.

```
android.widget.TextView.setText (TextView.java:6409)
com.henninghall.date_picker.generated.NumberPicker.updateInputTextView (NumberPicker.java:2011)
com.henninghall.date_picker.generated.NumberPicker.setValueInternal (NumberPicker.java:1806)
com.henninghall.date_picker.generated.NumberPicker.scrollBy (NumberPicker.java:1163)
com.henninghall.date_picker.generated.NumberPicker.moveToFinalScrollerPosition (NumberPicker.java:860)
com.henninghall.date_picker.generated.NumberPicker.changeValueByOne (NumberPicker.java:1825)
```

**Comment by dgrover-spotnana** [comment]
Hey @henninghall , any update on this ? Quite similar was reported on our Instabug today

`Device Info`
```
Device: Samsung Galaxy S22+ (SM-S906U)
OS: API Level 34 (Android 14)
```

`Version Info`
```
react-native: 0.72.12
react-native-date-picker: 5.0.2
```

`Stack Trace`
```
(ANR Input dispatching timed out (f5c628e com.app/com.app.MainActivity (server) is not responding. Waited 10000ms for MotionEvent)
	 at android.os.MessageQueue.removeMessages(MessageQueue.java:691)
	 at android.os.Handler.removeMessages(Handler.java:811)
	 at android.view.Choreographer.removeCallbacksInternal(Choreographer.java:719)
	 at android.view.Choreographer.removeCallbacks(Choreographer.java:707)
	 at android.view.View.removeCallbacks(View.java:21517)
	 at com.henninghall.date_picker.generated.NumberPicker$SetSelectionCommand.cancel(NumberPicker.java:2369)
	 at com.henninghall.date_picker.generated.NumberPicker$InputTextFilter.filter(NumberPicker.java:2194)
	 at android.widget.TextView.setText(TextView.java:7372)
	 at android.widget.TextView.setText(TextView.java:7334)
	 at android.widget.EditText.setText(EditText.java:149)
	 at android.widget.TextView.setText(TextView.java:7286)
	 at com.henninghall.date_picker.generated.NumberPicker.updateInputTextView(NumberPicker.java:2011)
	 at com.henninghall.date_picker.generated.NumberPicker.setValueInternal(NumberPicker.java:1806)
	 at com.henninghall.date_picker.generated.NumberPicker.scrollBy(NumberPicker.java:1155)
	 at com.henninghall.date_picker.generated.NumberPicker.moveToFinalScrollerPosition(NumberPicker.java:860)
	 at com.henninghall.date_picker.generated.NumberPicker.changeValueByOne(NumberPicker.java:1825)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.henninghall.date_picker.pickers.AndroidNative.changeValueByOne(AndroidNative.java:132)
	 at com.henninghall.date_picker.pickers.AndroidNative.-$$Nest$mchangeValueByOne(AndroidNative.java:0)
	 at com.henninghall.date_picker.pickers.AndroidNative$2.run(AndroidNative.java:155)
	 at android.os.Handler.handleCallback(Handler.java:958)
	 at android.os.Handler.dispatchMessage(Handler.java:99)
	 at android.os.Looper.loopOnce(Looper.java:230)
	 at android.os.Looper.loop(Looper.java:319)
	 at android.app.ActivityThread.main(ActivityThread.java:8919)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
, 0)
```

**Comment by dgrover-spotnana** [comment]
Hey @henninghall , any update on this ? Another report from our Instabug today

`Device Info`
```
Device: Samsung Galaxy S22 (SM-S901U)
OS: API Level 34 (Android 14)
```

`Version Info`
```
react-native: 0.72.12
react-native-date-picker: 5.0.2
```

`Stack Trace`
```
(ANR Input dispatching timed out (f478bc0 com.app/com.app.MainActivity (server) is not responding. Waited 10001ms for MotionEvent)
	 at android.os.MessageQueue.enqueueMessage(MessageQueue.java:583)
	 at android.os.Handler.enqueueMessage(Handler.java:786)
	 at android.os.Handler.sendMessageAtTime(Handler.java:735)
	 at android.view.ViewRootImpl$ViewRootHandler.sendMessageAtTime(ViewRootImpl.java:7157)
	 at android.os.Handler.sendMessageDelayed(Handler.java:705)
	 at android.os.Handler.post(Handler.java:435)
	 at android.view.View.post(View.java:21412)
	 at com.henninghall.date_picker.generated.NumberPicker$SetSelectionCommand.post(NumberPicker.java:2362)
	 at com.henninghall.date_picker.generated.NumberPicker.postSetSelectionCommand(NumberPicker.java:2145)
	 at com.henninghall.date_picker.generated.NumberPicker.-$$Nest$mpostSetSelectionCommand(NumberPicker.java:0)
	 at com.henninghall.date_picker.generated.NumberPicker$InputTextFilter.filter(NumberPicker.java:2234)
	 at android.widget.TextView.setText(TextView.java:7372)
	 at android.widget.TextView.setText(TextView.java:7334)
	 at android.widget.EditText.setText(EditText.java:149)
	 at android.widget.TextView.setText(TextView.java:7286)
	 at com.henninghall.date_picker.generated.NumberPicker.updateInputTextView(NumberPicker.java:2011)
	 at com.henninghall.date_picker.generated.NumberPicker.setValueInternal(NumberPicker.java:1806)
	 at com.henninghall.date_picker.generated.NumberPicker.scrollBy(NumberPicker.java:1163)
	 at com.henninghall.date_picker.generated.NumberPicker.moveToFinalScrollerPosition(NumberPicker.java:860)
	 at com.henninghall.date_picker.generated.NumberPicker.changeValueByOne(NumberPicker.java:1825)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.henninghall.date_picker.pickers.AndroidNative.changeValueByOne(AndroidNative.java:132)
	 at com.henninghall.date_picker.pickers.AndroidNative.-$$Nest$mchangeValueByOne(AndroidNative.java:0)
	 at com.henninghall.date_picker.pickers.AndroidNative$2.run(AndroidNative.java:155)
	 at android.os.Handler.handleCallback(Handler.java:958)
	 at android.os.Handler.dispatchMessage(Handler.java:99)
	 at android.os.Looper.loopOnce(Looper.java:230)
	 at android.os.Looper.loop(Looper.java:319)
	 at android.app.ActivityThread.main(ActivityThread.java:8919)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
, 0)
```

**Comment by dgrover-spotnana** [comment]
@henninghall , yet another report

`Device Info`
```
Device: Samsung Galaxy S24 (SM-S921U)
OS: API Level 34 (Android 14)
```

`Version Info`
```
react-native: 0.72.12
react-n

`Stack Trace`

```
(ANR Input dispatching timed out (a2242d9 com.app/com.app.MainActivity (server) is not responding. Waited 10000ms for MotionEvent)
	 at android.graphics.Paint.nGetFontMetricsInt(Native Method)
	 at android.graphics.Paint.getFontMetricsInt(Paint.java:2408)
	 at android.graphics.Paint.getFontMetricsInt(Paint.java:2413)
	 at android.text.DynamicLayout.contentMayProtrudeFromLineTopOrBottom(DynamicLayout.java:718)
	 at android.text.DynamicLayout.reflow(DynamicLayout.java:681)
	 at android.text.DynamicLayout.generate(DynamicLayout.java:480)
	 at android.text.DynamicLayout.<init>(DynamicLayout.java:400)
	 at android.text.DynamicLayout.<init>(Unknown Source:0)
	 at android.text.DynamicLayout$Builder.build(DynamicLayout.java:281)
	 at android.widget.TextView.makeSingleLayout(TextView.java:11334)
	 at android.widget.TextView.makeNewLayout(TextView.java:11189)
	 at android.widget.TextView.checkForRelayout(TextView.java:11944)
	 at android.widget.TextView.setText(TextView.java:7555)
	 at android.widget.TextView.setText(TextView.java:7342)
	 at android.widget.EditText.setText(EditText.java:149)
	 at android.widget.TextView.setText(TextView.java:7294)
	 at com.henninghall.date_picker.generated.NumberPicker.updateInputTextView(NumberPicker.java:2011)
	 at com.henninghall.date_picker.generated.NumberPicker.setValueInternal(NumberPicker.java:1806)
	 at com.henninghall.date_picker.generated.NumberPicker.scrollBy(NumberPicker.java:1163)
	 at com.henninghall.date_picker.generated.NumberPicker.moveToFinalScrollerPosition(NumberPicker.java:860)
	 at com.henninghall.date_picker.generated.NumberPicker.changeValueByOne(NumberPicker.java:1825)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.henninghall.date_picker.pickers.AndroidNative.changeValueByOne(AndroidNative.java:132)
	 at com.henninghall.date_picker.pickers.AndroidNative.-$$Nest$mchangeValueByOne(AndroidNative.java:0)
	 at com.henninghall.date_picker.pickers.AndroidNative$2.run(AndroidNative.java:155)
	 at android.os.Handler.handleCallback(Handler.java:958)
	 at android.os.Handler.dispatchMessage(Handler.java:99)
	 at android.os.Looper.loopOnce(Looper.java:230)
	 at android.os.Looper.loop(Looper.java:319)
	 at android.app.ActivityThread.main(ActivityThread.java:9063)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
, 0)
```

**Comment by gandarain** [comment]
Any update on this @henninghall ?
This issue still occurs.

react-native: 0.72.13
react-native-date-picker: 4.4.0

**Comment by gandarain** [comment]
> Not just Android 11. I have got ANR reports from Android 13 as well. I will roll back to 4.4.2 for now.
> 
> ```
> com.henninghall.date_picker.generated.NumberPicker.updateInputTextView
> ANR triggered by main thread waiting for too long
> ```
> 
> ```
> com.henninghall.date_picker.generated.NumberPicker.updateInputTextView (NumberPicker.java:2011)
> com.henninghall.date_picker.generated.NumberPicker.setValueInternal (NumberPicker.java:1806)
> com.henninghall.date_picker.generated.NumberPicker.scrollBy (NumberPicker.java:1163)
> com.henninghall.date_picker.generated.NumberPicker.moveToFinalScrollerPosition (NumberPicker.java:860)
> com.henninghall.date_picker.generated.NumberPicker.changeValueByOne (NumberPicker.java:1825)
> ```

In version 4.4.2, the issue still happen?
I am using version 4.4.0, this issue still happen.

**Comment by guptayush** [comment]
Use @react-native-community/datetimepicker
