### ISSUE TITLE
App Crash in release when proguard is enabled

### ISSUE THREAD

**Issue by cparashar007** [henninghall/react-native-date-picker#519]
**Describe the bug**
App got crashed when release on play store with proguard enabled as described in documentation.
Here is the error stack strace:

Fatal Exception: java.lang.ExceptionInInitializerError
       at net.time4j.android.spi.AndroidResourceLoader$I18nDataHolder.<clinit>(AndroidResourceLoader.java:474)
       at net.time4j.android.spi.AndroidResourceLoader$I18nDataHolder.access$1200(AndroidResourceLoader.java:464)
       at net.time4j.android.spi.AndroidResourceLoader$LazyWeekdata.iterator(AndroidResourceLoader.java:373)
       at net.time4j.Weekmodel.<clinit>(Weekmodel.java:133)
       at net.time4j.PlainTimestamp.<clinit>(PlainTimestamp.java:244)
       at net.time4j.PlainTimestamp.of(PlainTimestamp.java:464)
       at net.time4j.PlainDate.at(PlainDate.java:1119)
       at net.time4j.android.ApplicationStarter.initialize(ApplicationStarter.java:170)
       at net.time4j.android.ApplicationStarter.initialize(ApplicationStarter.java:120)
       at com.henninghall.date_picker.DatePickerModule.<init>(DatePickerModule.java:24)
       at com.henninghall.date_picker.DatePickerPackage.createNativeModules(DatePickerPackage.java:19)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
       at java.lang.Thread.run(Thread.java:764)
       
       Caused by java.util.MissingResourceException: Cannot find resource bundle for: calendar/names/iso8601/iso8601_hi_IN.properties
       at net.time4j.i18n.PropertyBundle.load(PropertyBundle.java:192)
       at net.time4j.i18n.IsoTextProviderSPI.<clinit>(IsoTextProviderSPI.java:59)
       at net.time4j.android.spi.AndroidResourceLoader$I18nDataHolder.<clinit>(AndroidResourceLoader.java:474)
       at net.time4j.android.spi.AndroidResourceLoader$I18nDataHolder.access$1200(AndroidResourceLoader.java:464)
       at net.time4j.android.spi.AndroidResourceLoader$LazyWeekdata.iterator(AndroidResourceLoader.java:373)
       at net.time4j.Weekmodel.<clinit>(Weekmodel.java:133)
       at net.time4j.PlainTimestamp.<clinit>(PlainTimestamp.java:244)
       at net.time4j.PlainTimestamp.of(PlainTimestamp.java:464)
       at net.time4j.PlainDate.at(PlainDate.java:1119)
       at net.time4j.android.ApplicationStarter.initialize(ApplicationStarter.java:170)
       at net.time4j.android.ApplicationStarter.initialize(ApplicationStarter.java:120)
       at com.henninghall.date_picker.DatePickerModule.<init>(DatePickerModule.java:24)
       at com.henninghall.date_picker.DatePickerPackage.createNativeModules(DatePickerPackage.java:19)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
       at java.lang.Thread.run(Thread.java:764)

  OS: android
  React Native version "0.63.4",
  react-native-date-picker version 4.2.1.
  97% carsh on Android 10.

**Comment by henninghall** [comment]
There is instructions in README on how to avoid proguard crashes.

**Comment by cparashar007** [comment]
as described in ticket i already implemented the proguard rules as per documentation. still i got these in crashlytics.

**Comment by ngandhy** [comment]
@cparashar007 - in app/build.gradle what is your jscFlavor value set to? Does setting it to 'org.webkit:android-jsc-intl:+'
 fix the issue? Please lmk if it does!
