### ISSUE TITLE
Biuld failed with an exception

### ISSUE THREAD

**Issue by Arremeza** [henninghall/react-native-date-picker#622]
So y have this FAILURE after installing date-picker dependencies, the app wont build anymore it gives me this error

*FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-date-picker'.
> Could not open cp_proj generic class cache for build file 'C:\Users\Alexis\Documents\Cursos\cursoReactUdemy\citas\node_modules\react-native-date-picker\android\build.gradle' (C:\Users\Alexis\.gradle\caches\7.5.1\scripts\d4r1g3ri9p7o7hwfh2k72454r).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 12s

    at makeError (C:\Users\Alexis\Documents\Cursos\cursoReactUdemy\citas\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\Alexis\Documents\Cursos\cursoReactUdemy\citas\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async runOnAllDevices (C:\Users\Alexis\Documents\Cursos\cursoReactUdemy\citas\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (C:\Users\Alexis\Documents\Cursos\cursoReactUdemy\citas\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.

The error occurs when I try to run the app via npx react-native run-android
```
Any solutions? thanks.
 - OS: [Android]
 - React Native version [9.5.0]
 - react-native-date-picker version [4.2.9]

**Comment by henninghall** [comment]
I think this is a problem with your Java / gradle setup. https://stackoverflow.com/questions/68597899/bug-exception-in-phase-semantic-analysis-in-source-unit-buildscript-unsup
