### ISSUE TITLE
Error constantly showing and Error: Unable to resolve module ./Libraries/Components/DatePicker/DatePickerIOS from /projectPath/node_modules/react-native/index.js: 

### ISSUE THREAD

**Issue by shay-te** [henninghall/react-native-date-picker#680]
```
Error: Unable to resolve module ./Libraries/Components/DatePicker/DatePickerIOS from /projectPath/node_modules/react-native/index.js: 

None of these files exist:
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg)
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS/index(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg)
  15 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
  16 | import typeof Button from './Libraries/Components/Button';
> 17 | import typeof DatePickerIOS from './Libraries/Components/DatePicker/DatePickerIOS';
     |                                   ^
  18 | import typeof DrawerLayoutAndroid from './Libraries/Components/DrawerAndroid/DrawerLayoutAndroid';
  19 | import typeof FlatList from './Libraries/Lists/FlatList';
  20 | import typeof Image from './Libraries/Image/Image';
    at ModuleResolver.resolveDependency (projectPath/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (projectPath/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (projectPath/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (projectPath/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at projectPath/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (projectPath/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (projectPath/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (projectPath/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 2)
 LOG  MESSAGING_CLIENT.onopen

```

**Comment by henninghall** [comment]
This is a a react native issue https://github.com/facebook/react-native/issues/36794
