### ISSUE TITLE
Cannot find DatePickerIOS module for 'react-native-date-picker' on only IOS

### ISSUE THREAD

**Issue by gunjankumar58** [henninghall/react-native-date-picker#746]
**Output of npx react-native info**
System:
    OS: macOS 14.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 461.74 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: Not Found
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.14.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11076708
    Xcode: 15.1/15C65 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Steps to reproduce**
import DatePicker from 'react-native-date-picker';

<DatePicker
        modal
        open={dateOpen}
        date={date
        mode="date"
        onConfirm={date => {setDate(date)}}
        onCancel={() => {
          setDateOpen(false);
        }}
      />
**Error:**
None of these files exist:
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS/index(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  15 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
  16 | import typeof Button from './Libraries/Components/Button';
> 17 | import typeof DatePickerIOS from './Libraries/Components/DatePicker/DatePickerIOS';
     |                                   ^
  18 | import typeof DrawerLayoutAndroid from './Libraries/Components/DrawerAndroid/DrawerLayoutAndroid';
  19 | import typeof FlatList from './Libraries/Lists/FlatList';
  20 | import typeof Image from './Libraries/Image/Image';
    at ModuleResolver.resolveDependency (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:137:15)
    at DependencyGraph.resolveDependency (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 0)
    at async Graph._processModule (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._traverseDependenciesForSingleFile (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/DeltaBundler/Graph.js:207:5)
Error: Unable to resolve module ./Libraries/Components/DatePicker/DatePickerIOS from /Users/user/Desktop/Work/synkbooks_app_v1/node_modules/react-native/index.js: 

ios simulator version: ios 17.2
![Uploading Screenshot 2023-12-29 at 12.23.37 PM.png…]()

**Comment by leohooho** [comment]
same

**Comment by henninghall** [comment]
Unrelated to this package. It’s an issue in react native itself: https://github.com/facebook/react-native/issues/36794

Upgrading react native version might help.
